LOAD DATA
INFILE 'C:\lab11\exportOracle.csv'
APPEND
INTO TABLE LICENSES_class
FIELDS TERMINATED BY ","
(
  SOFTWARE_ID,
  USER_ID,
  START_DATE DATE "dd/mm/yyyy",
  END_DATE DATE "dd/mm/yyyy",
  LICENSE_COST "ROUND(:LICENSE_COST,1)",
  CLASS_NAME "UPPER(:CLASS_NAME)"
)