
CREATE TABLE LICENSES_class (
    SOFTWARE_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    LICENSE_COST DECIMAL(10, 2) NOT NULL,
	CLASS_NAME varchar(50) NOT NULL
);


CREATE OR REPLACE TYPE LICENSES_classes AS OBJECT (
    SOFTWARE_ID NUMBER,
    USER_ID NUMBER,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    LICENSE_COST NUMBER(10, 2),
    CLASS_NAME varchar(50)
);

CREATE OR REPLACE TYPE LicensesTableType AS TABLE OF LICENSES_classes;

CREATE OR REPLACE FUNCTION GetLICENSESByDateRange
(
    START_DATE_range IN DATE,
    END_DATE_range IN DATE
)
RETURN LicensesTableType PIPELINED
AS
BEGIN
    FOR LICENSES_class_now IN (
        SELECT SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST, CLASS_NAME
        FROM LICENSES_class
        WHERE START_DATE >= START_DATE_range AND END_DATE <= END_DATE_range
    ) LOOP
        PIPE ROW (LICENSES_classes(LICENSES_class_now.SOFTWARE_ID, LICENSES_class_now.USER_ID, LICENSES_class_now.START_DATE, LICENSES_class_now.END_DATE, LICENSES_class_now.LICENSE_COST, LICENSES_class_now.CLASS_NAME));
    END LOOP;

    RETURN;
END;
/

INSERT INTO LICENSES_class (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST, CLASS_NAME)
VALUES
    (1, 1, TO_DATE('2024-02-17', 'YYYY-MM-DD'), TO_DATE('20/02/2024', 'DD/MM/YYYY'), 155.56, 'Class1');

select * from LICENSES_class;

--sqlldr system/Qwerty12345 CONTROL='C:\lab11\control.ctl'
SELECT * FROM TABLE(CAST(GetLICENSESByDateRange(TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-04-10', 'YYYY-MM-DD')) AS LicensesTableType));



