-- Вставка данных в таблицу USERS
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, DEVICE, ROLE) VALUES
('user1', 'password1', 'user1@example.com', 'device1', 'role1');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, DEVICE, ROLE) VALUES
('user2', 'password2', 'user2@example.com', 'device2', 'role2');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, DEVICE, ROLE) VALUES
('user3', 'password3', 'user3@example.com', 'device3', 'role3');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, DEVICE, ROLE) VALUES
('user4', 'password4', 'user4@example.com', 'device4', 'role4');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, DEVICE, ROLE) VALUES
('user5', 'password5', 'user5@example.com', 'device5', 'role5');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, DEVICE, ROLE) VALUES
('user6', 'password6', 'user6@example.com', 'device6', 'role6');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, DEVICE, ROLE) VALUES
('user7', 'password7', 'user7@example.com', 'device7', 'role7');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, DEVICE, ROLE) VALUES
('user8', 'password8', 'user8@example.com', 'device8', 'role8');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, DEVICE, ROLE) VALUES
('user9', 'password9', 'user9@example.com', 'device9', 'role9');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, DEVICE, ROLE) VALUES
('user10', 'password10', 'user10@example.com', 'device10', 'role10');


-- Вставка данных в таблицу SOFTWARE
INSERT INTO SOFTWARE (NAME, VERSION, VENDOR, LICENSE_TYPE) VALUES
('Software1', '1.0', 'Vendor1', 'Type1');

INSERT INTO SOFTWARE (NAME, VERSION, VENDOR, LICENSE_TYPE) VALUES
('Software2', '2.0', 'Vendor2', 'Type2');

INSERT INTO SOFTWARE (NAME, VERSION, VENDOR, LICENSE_TYPE) VALUES
('Software3', '1.0', 'Vendor3', 'Type3');

INSERT INTO SOFTWARE (NAME, VERSION, VENDOR, LICENSE_TYPE) VALUES
('Software4', '2.0', 'Vendor4', 'Type4');

INSERT INTO SOFTWARE (NAME, VERSION, VENDOR, LICENSE_TYPE) VALUES
('Software5', '1.0', 'Vendor5', 'Type5');

INSERT INTO SOFTWARE (NAME, VERSION, VENDOR, LICENSE_TYPE) VALUES
('Software6', '2.0', 'Vendor6', 'Type6');

INSERT INTO SOFTWARE (NAME, VERSION, VENDOR, LICENSE_TYPE) VALUES
('Software7', '1.0', 'Vendor7', 'Type7');

INSERT INTO SOFTWARE (NAME, VERSION, VENDOR, LICENSE_TYPE) VALUES
('Software8', '2.0', 'Vendor8', 'Type8');

INSERT INTO SOFTWARE (NAME, VERSION, VENDOR, LICENSE_TYPE) VALUES
('Software9', '1.0', 'Vendor9', 'Type9');

INSERT INTO SOFTWARE (NAME, VERSION, VENDOR, LICENSE_TYPE) VALUES
('Software10', '2.0', 'Vendor10', 'Type10');


-- Вставка данных в таблицу LICENSES
INSERT INTO LICENSES (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST) VALUES
(1, 1, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 100.00);

INSERT INTO LICENSES (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST) VALUES
(2, 2, TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 120.00);

INSERT INTO LICENSES (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST) VALUES
(3, 3, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 130.00);

INSERT INTO LICENSES (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST) VALUES
(4, 4, TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 140.00);

INSERT INTO LICENSES (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST) VALUES
(5, 5, TO_DATE('2024-06-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 150.00);

INSERT INTO LICENSES (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST) VALUES
(6, 6, TO_DATE('2024-08-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 160.00);

INSERT INTO LICENSES (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST) VALUES
(7, 7, TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 170.00);

INSERT INTO LICENSES (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST) VALUES
(8, 8, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 180.00);

INSERT INTO LICENSES (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST) VALUES
(9, 9, TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 190.00);

INSERT INTO LICENSES (SOFTWARE_ID, USER_ID, START_DATE, END_DATE, LICENSE_COST) VALUES
(10, 10, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 200.00);

INSERT INTO ROOM_CLASSES (CLASS_NAME, USER_ID) VALUES
('Class1', 1);

INSERT INTO ROOM_CLASSES (CLASS_NAME, USER_ID) VALUES
('Class2', 2);
INSERT INTO ROOM_CLASSES (CLASS_NAME, USER_ID) VALUES
('Class3', 3);

INSERT INTO ROOM_CLASSES (CLASS_NAME, USER_ID) VALUES
('Class4', 4);

INSERT INTO ROOM_CLASSES (CLASS_NAME, USER_ID) VALUES
('Class5', 5);

INSERT INTO ROOM_CLASSES (CLASS_NAME, USER_ID) VALUES
('Class6', 6);

INSERT INTO ROOM_CLASSES (CLASS_NAME, USER_ID) VALUES
('Class7', 7);

INSERT INTO ROOM_CLASSES (CLASS_NAME, USER_ID) VALUES
('Class8', 8);

INSERT INTO ROOM_CLASSES (CLASS_NAME, USER_ID) VALUES
('Class9', 9);

INSERT INTO ROOM_CLASSES (CLASS_NAME, USER_ID) VALUES
('Class10', 10);

INSERT INTO CLASS_HISTORY (CLASS_ID, NEW_CLASS_NAME, CHANGE_DATE) VALUES
(1, 'NewClass1', TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO CLASS_HISTORY (CLASS_ID, NEW_CLASS_NAME, CHANGE_DATE) VALUES
(2, 'NewClass2', TO_DATE('2024-01-01', 'YYYY-MM-DD'));
INSERT INTO CLASS_HISTORY (CLASS_ID, NEW_CLASS_NAME, CHANGE_DATE) VALUES
(3, 'NewClass3', TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO CLASS_HISTORY (CLASS_ID, NEW_CLASS_NAME, CHANGE_DATE) VALUES
(4, 'NewClass4', TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO CLASS_HISTORY (CLASS_ID, NEW_CLASS_NAME, CHANGE_DATE) VALUES
(5, 'NewClass5', TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO CLASS_HISTORY (CLASS_ID, NEW_CLASS_NAME, CHANGE_DATE) VALUES
(6, 'NewClass6', TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO CLASS_HISTORY (CLASS_ID, NEW_CLASS_NAME, CHANGE_DATE) VALUES
(7, 'NewClass7', TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO CLASS_HISTORY (CLASS_ID, NEW_CLASS_NAME, CHANGE_DATE) VALUES
(8, 'NewClass8', TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO CLASS_HISTORY (CLASS_ID, NEW_CLASS_NAME, CHANGE_DATE) VALUES
(9, 'NewClass9', TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO CLASS_HISTORY (CLASS_ID, NEW_CLASS_NAME, CHANGE_DATE) VALUES
(10, 'NewClass10', TO_DATE('2024-01-01', 'YYYY-MM-DD'));