-- СОЗДАНИЕ ТАБЛИЦЫ "ПОЛЬЗОВАТЕЛИ"
CREATE TABLE USERS (
USER_ID INT PRIMARY KEY,
USERNAME NVARCHAR(50),
PASSWORD NVARCHAR(50),
EMAIL NVARCHAR(100),
ROLE NVARCHAR(50)
);

-- СОЗДАНИЕ ТАБЛИЦЫ "ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ"
CREATE TABLE SOFTWARE (
SOFTWARE_ID INT PRIMARY KEY,
NAME NVARCHAR(100),
VERSION NVARCHAR(50),
VENDOR NVARCHAR(100),
LICENSE_TYPE NVARCHAR(50)
);

-- СОЗДАНИЕ ТАБЛИЦЫ "ЛИЦЕНЗИИ"
CREATE TABLE LICENSES (
LICENSE_ID INT PRIMARY KEY,
SOFTWARE_ID INT,
USER_ID INT,
START_DATE DATE,
END_DATE DATE,
FOREIGN KEY (SOFTWARE_ID) REFERENCES SOFTWARE(SOFTWARE_ID),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
